# Generated by Django 4.2.5 on 2023-10-26 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='text',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
