# Generated by Django 4.2.5 on 2023-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='text',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
