# Generated by Django 4.2.5 on 2023-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0004_alter_images_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='indifer',
            field=models.CharField(choices=[['1', '1'], ['2', '2']], default=1, max_length=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
