# Generated by Django 4.2.5 on 2023-10-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0010_alter_images_indifer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
