# Generated by Django 4.2.5 on 2023-10-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0011_alter_images_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('indifer', 'place')},
        ),
    ]
